/* ═══════════════════════════════════════════════════════════════
   CSSExporter — Generate production-ready CSS+JS with baked values
   Downloads customized module files ready for implementation.
   ═══════════════════════════════════════════════════════════════ */
const CSSExporter = {
  async exportModule(moduleId) {
    const mod = await ModuleRegistry.get(moduleId);
    if (!mod) return;

    let css = mod.cssSource || '';
    const overrides = mod.cssOverrides || {};

    // Apply overrides: replace var declarations with overridden values
    for (const [varName, value] of Object.entries(overrides)) {
      const escapedName = varName.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
      const regex = new RegExp(escapedName + '\\s*:\\s*[^;]+', 'g');
      css = css.replace(regex, varName + ': ' + value);
    }

    // Generate header comment
    const header = `/* ═══════════════════════════════════════════════
   Module: ${mod.name}
   Exported: ${new Date().toISOString()}
   Customized with Feature Brainstorm Hub V4
   ═══════════════════════════════════════════════ */\n\n`;

    const files = [];

    // CSS file
    if (css) {
      files.push({
        name: mod.cssFileName || mod.name.toLowerCase().replace(/\s+/g, '-') + '.css',
        content: header + css
      });
    }

    // JS file
    if (mod.jsSource) {
      files.push({
        name: mod.jsFileName || mod.name.toLowerCase().replace(/\s+/g, '-') + '.js',
        content: header + mod.jsSource
      });
    }

    // Python files
    if (mod.pythonScripts?.length) {
      mod.pythonScripts.forEach(py => {
        files.push({ name: py.name, content: py.source });
      });
    }

    // Integration readme
    const project = App.currentProject;
    if (project) {
      const slug = mod.name.toLowerCase().replace(/[^a-z0-9]+/g, '-');
      const readme = `# ${mod.name} — Integration Guide

## Files
${files.map(f => '- ' + f.name).join('\n')}

## Integration Steps
1. Copy CSS file to: css/${slug}.css
2. Copy JS file to: js/${slug}.js
${mod.pythonScripts?.length ? '3. Copy Python files to: ' + (project.pythonDir || 'python/') : ''}

## Add to index.html
\`\`\`html
<!-- In <head> -->
<link rel="stylesheet" href="css/${slug}.css">

<!-- Before </body> -->
<script src="js/${slug}.js"><\/script>
\`\`\`

## Theme Variables Used
${Object.entries(overrides).map(([k, v]) => `${k}: ${v}`).join('\n') || 'Using defaults'}

Generated by Feature Brainstorm Hub V4
`;
      files.push({ name: 'INTEGRATION.md', content: readme });
    }

    // Download all files
    FileIO.downloadBundle(files);
    Toast.show(`Exported ${files.length} files! ⬇️`);
  }
};
